In [1]:
import numpy as np

In [2]:
#reshape行数列数乘积需要保证等于6
array_1 =  np.arange(6)
x = array_1.reshape((2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
#arange类似于python的range函数
array_2 = np.arange(1, 10, 2, dtype=np.float)
array_2

array([ 1.,  3.,  5.,  7.,  9.])

In [4]:
print '维度数量：', x.ndim
print '数组的形状：', x.shape
print '数组的元素类型：', x.dtype
print '数组的元素数量：', x.size

维度数量： 2
数组的形状： (2L, 3L)
数组的元素类型： int32
数组的元素数量： 6


In [5]:
array_3 = np.array(range(4, 20, 2), dtype=np.int)
array_4 = np.array([[1,2,324], [23,45,76]])
print array_3
print array_4

[ 4  6  8 10 12 14 16 18]
[[  1   2 324]
 [ 23  45  76]]


In [6]:
array_one = np.ones(3, dtype=np.int)
array_one_1 = np.ones((3,4), dtype=np.int)
print array_one
print array_one_1

[1 1 1]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
array_empty = np.empty(3)
array_empty_1 = np.empty((3,4), dtype=np.int)
#不指定数据类型则默认是float类型,数据则是浮点型随机数据
array_empty_2 = np.empty((3,4))
print array_empty
print array_empty_1
print array_empty_2

[  6.09738745e-316   6.09738745e-316   6.07604658e-316]
[[  49838008          0   49837984          0]
 [  72009528          0 1629465688          0]
 [ 122995400          0  122998024          0]]
[[  6.07780190e-316   6.07792759e-316   6.07791336e-316   6.07792285e-316]
 [  6.07785882e-316   6.07790862e-316   2.45494895e-316   0.00000000e+000]
 [  0.00000000e+000   0.00000000e+000   0.00000000e+000   0.00000000e+000]]


In [8]:
array_zeros = np.zeros(3)
array_zeros_1 = np.zeros((3,4), dtype=np.int)
#不指定数据类型则默认是float类型
array_zeros_2 = np.zeros((3,4))
print array_zeros
print array_zeros_1
print array_zeros_2

[ 0.  0.  0.]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [9]:
#改变已有数组的数据类型
print x.dtype
change_x = x.astype(np.float)
print change_x.dtype

int32
float64


In [10]:
#reshape修改数组形状，-1代表当前维度的元素个数，自动计算
reshape_array_3 = array_3.reshape(4,-1)
reshape_array_3

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [11]:
b = np.array([[0, 1], [2, 3]])
m = np.array([[0, 1], [2, 3]])
b.resize((2,1))
m.resize((2,3))
print b
print m

[[0]
 [1]]
[[0 1 2]
 [3 0 0]]


In [12]:
#矩阵的乘积 其中一个矩阵的行等于另一个矩阵的列
m = np.arange(1, 12, 2)
m = m.reshape((2,3))
print 'm:', m

n = np.arange(2, 14, 2, dtype=np.float)
n = n.reshape((3,2))
print 'n:', n

print 'np.dot(m, n):', np.dot(m, n)

m: [[ 1  3  5]
 [ 7  9 11]]
n: [[  2.   4.]
 [  6.   8.]
 [ 10.  12.]]
np.dot(m, n): [[  70.   88.]
 [ 178.  232.]]


In [13]:
#ndarray-多维数组的索引
test_array = np.array([[[2, 3, 4, 5], 
                        [1, 3, 4, 9]],
                       [[0, 3, 4, 8],
                        [2, 4, 9, 4]],
                       [[1, 4, 5, 8],
                        [2, 5, 6, 8]],
                       [[2, 3, 6, 8],
                        [3, 4, 8, 9]]])
print 'test_array[1]:', test_array[1]
print 'test_array[1][0]:', test_array[1][0]
print 'test_array[1][0][1:3]:', test_array[1][0][1:3]
print 'test_array[1, :, 1:3]:', test_array[1, :, 1:3]
print 'test_array[1, :][1:]:', test_array[1, :][1:]
print 'test_array[1, :][0]:', test_array[1, :][0]
print 'test_array[1, :]:', test_array[1, :]
print 'test_array[1][:]:', test_array[1][:]

test_array[1]: [[0 3 4 8]
 [2 4 9 4]]
test_array[1][0]: [0 3 4 8]
test_array[1][0][1:3]: [3 4]
test_array[1, :, 1:3]: [[3 4]
 [4 9]]
test_array[1, :][1:]: [[2 4 9 4]]
test_array[1, :][0]: [0 3 4 8]
test_array[1, :]: [[0 3 4 8]
 [2 4 9 4]]
test_array[1][:]: [[0 3 4 8]
 [2 4 9 4]]


In [14]:
print

In [15]:
#ndarray-布尔类型索引 
#numpy中不能使用过python的and、or、not操作，使用逻辑与(&)，逻辑或(|)，逻辑非(~)来替换
names = np.array(['Jeff', 'Tom', 'John', 'Lily'])
scores = np.array([[94, 78, 91, 67],
                   [89, 70, 98, 100], 
                   [80, 79, 82, 92],
                   [100, 59, 93, 95]])
classes = np.array([u'语文', u'英语', u'物理', u'数学'])
print scores[names == 'Jeff']
print scores[names == 'Jeff'].reshape((-1,))[classes == u'物理']
print scores[(names == 'Jeff') | (names == 'Lily')]
print scores[(names != 'Jeff') & (names != 'Lily') & (names != 'John')]

[[94 78 91 67]]
[91]
[[ 94  78  91  67]
 [100  59  93  95]]
[[ 89  70  98 100]]


In [17]:
#ndarray-花式索引
array = np.arange(32).reshape(8, 4)
print array, type(array)
#获取第0、3、5行的数据
print '获取第0、3、5行的数据:\n', array[[0, 3, 5]]
#获取第(0, 0)，(3, 3)，(5, 3)这三个索引位置的数据
print '获取第(0, 0)，(3, 3)，(5, 3)这三个索引位置的数据:', array[[0,3,5],[0,3,3]]
#获取第0、3、5行的第0、2、3列的数据
print '获取第0、3、5行的第0、2、3列的数据:', array[[0,3,5]].T[[0,2,3]].T #通过转置矩阵实现
print '获取第0、3、5行的第0、2、3列的数据:', array[np.ix_([0,3,5],[0,2,3])]
#np.ix_函数会产生一个索引器
print 'np.ix_函数会产生一个索引器:', np.ix_([0,3,5],[0,2,3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] <type 'numpy.ndarray'>
获取第0、3、5行的数据:
[[ 0  1  2  3]
 [12 13 14 15]
 [20 21 22 23]]
获取第(0, 0)，(3, 3)，(5, 3)这三个索引位置的数据: [ 0 15 23]
获取第0、3、5行的第0、2、3列的数据: [[ 0  2  3]
 [12 14 15]
 [20 22 23]]
获取第0、3、5行的第0、2、3列的数据: [[ 0  2  3]
 [12 14 15]
 [20 22 23]]
np.ix_函数会产生一个索引器: (array([[0],
       [3],
       [5]]), array([[0, 2, 3]]))


In [18]:
#数组的转置是指将shape进行重置操作，并将其值重置为原始shape元祖的倒置，比如原始的shape值为：(2,3,4),转置后的新元祖shape值为（4,3,2）
#对于二维数组而言(矩阵)数组的转置其实就是矩阵的的转置
#可以通过调用数组的transpose函数或者T属性进行数组转置操作
